export type AgentModuleDef = { key: string; title: string; emoji: string };

export const MODULE_LIST: AgentModuleDef[] = [
  { key: "identidade", title: "Identidade", emoji: "🪪" },
  { key: "spotify", title: "Spotify", emoji: "🎵" },
  { key: "youtube", title: "YouTube", emoji: "▶️" },
  { key: "instagram", title: "Instagram", emoji: "📸" },
  { key: "tiktok", title: "TikTok", emoji: "🎬" },
  { key: "kwai", title: "Kwai", emoji: "🌟" },
  { key: "facebook", title: "Facebook", emoji: "👍" },
  { key: "seo_google", title: "SEO e Google", emoji: "🌐" },
  { key: "calculo_preco", title: "Cálculo de Preço", emoji: "🧮" },
  { key: "estrangeiros", title: "Clientes Estrangeiros", emoji: "🌍" },
  { key: "pagamentos", title: "Pagamentos", emoji: "💳" },
  { key: "fluxo_vendas", title: "Fluxo de Vendas", emoji: "🛒" },
  { key: "tecnicas_vendas", title: "Técnicas de Vendas", emoji: "🎯" },
  { key: "objecoes", title: "Objeções", emoji: "🛡️" },
  { key: "upsell", title: "Upsell", emoji: "📈" },
  { key: "teste_gratis", title: "Teste Grátis", emoji: "🎁" },
  { key: "suporte", title: "Suporte", emoji: "🛠️" },
  { key: "historico_refil", title: "Histórico e Refil", emoji: "📜" },
  { key: "desconto_niveis", title: "Desconto e Níveis", emoji: "🏅" },
  { key: "classificacao_contatos", title: "Classificação de Contatos", emoji: "🌡️" },
  { key: "educacao", title: "Educação e Orientação", emoji: "🎓" },
  { key: "regras_proibidas", title: "Regras Proibidas", emoji: "🚫" },
  { key: "comportamento_humano", title: "Comportamento Humano", emoji: "🧠" },
  { key: "texto_ou_audio", title: "Texto ou Áudio", emoji: "🎙️" },
  { key: "disparo_ativo", title: "Disparo Ativo", emoji: "📣" },
  { key: "avisos", title: "Avisos e Comunicados", emoji: "📢" },
  { key: "encerramento", title: "Encerramento de Conversa", emoji: "🛑" },
  { key: "silencio_cliente", title: "Silêncio do Cliente", emoji: "🤐" },
  { key: "como_usar_painel", title: "Como Usar o Painel", emoji: "🧭" },
  { key: "regras_gerais", title: "Regras Gerais Absolutas", emoji: "⚖️" },
  { key: "follow_up", title: "Follow-up Inteligente", emoji: "⏰" },
  { key: "prova_social", title: "Prova Social Contextual", emoji: "🌟" },
  { key: "ancoragem_valor", title: "Ancoragem de Valor", emoji: "⚓" },
  { key: "fechamento_3", title: "Fechamento em 3 Passos", emoji: "✅" },
  { key: "recuperacao_silencio", title: "Recuperação Pós Silêncio", emoji: "🔁" },
  { key: "palavras_vendem", title: "Palavras que Vendem", emoji: "🗣️" },
  { key: "inteligencia_algoritmo", title: "Inteligência de Algoritmo", emoji: "📊" },
  { key: "pipeline_futuro", title: "Pipeline de Cliente Futuro", emoji: "🌱" },
  { key: "pos_venda", title: "Pós Venda", emoji: "📦" },
  { key: "inteligencia_emocional", title: "Inteligência Emocional", emoji: "❤️" },
  { key: "guia_visual_painel", title: "Guia Visual do Painel", emoji: "🖼️" },
  { key: "reativacao_frio", title: "Reativação de Cliente Frio", emoji: "🧊" },
  { key: "musica_cliente", title: "Música do Cliente", emoji: "🎧" },
  { key: "aprendizado_continuo", title: "Aprendizado Contínuo", emoji: "📚" },
];

export const DEFAULT_MODULES: Record<string, string> = {};
