import { randomUUID } from "node:crypto";
import { acquireAgentConversationLock,refreshAgentConversationLock,releaseAgentConversationLock } from "@/lib/agent-v3/conversation-lock.server";
import { startAgentConversationLockHeartbeat } from "@/lib/agent-v3/conversation-lock-heartbeat.server";
import { blocksAutomaticAgentAfterFunnelClassification,classifyWelcomeFunnelExecution,mayStartWelcomeFunnelExecution,type WelcomeFunnelExecutionClass } from "@/lib/welcome-funnel-execution-gate.server";
import { runWelcomeFunnelSequence,type WelcomeFunnelRuntime } from "@/lib/welcome-funnel-runner.server";
async function removeFreshLegacyClaimBeforeDurableStart(p:{supabaseAdmin:any;funnelId:string;contactId:string;userId:string;workspaceId:string}){const{error}=await p.supabaseAdmin.rpc("clear_fresh_welcome_funnel_legacy_claim",{p_funnel_id:p.funnelId,p_contact_id:p.contactId,p_user_id:p.userId,p_workspace_id:p.workspaceId});if(error)throw error;}
export async function resumeRecoveredWelcomeFunnel(p:{supabaseAdmin:any;funnel:WelcomeFunnelRuntime;contactId:string;conversationId:string;userId:string;workspaceId:string;phone:string;creds:{uazapi_url:string;uazapi_token:string}}):Promise<WelcomeFunnelOrchestrationResult>{
 const identity={supabaseAdmin:p.supabaseAdmin,funnelId:p.funnel.id,contactId:p.contactId,conversationId:p.conversationId,userId:p.userId,workspaceId:p.workspaceId};
 const holder=`welcome-funnel-resume:${p.funnel.id}:${randomUUID()}`;const acquired=await acquireAgentConversationLock(p.supabaseAdmin,p.conversationId,holder);if(!acquired)return{status:"busy",classification:"unclaimed"};let leaseError:Error|null=null;
 const assertExecutionOwnership=async()=>{if(leaseError)throw leaseError;const owned=await refreshAgentConversationLock(p.supabaseAdmin,p.conversationId,holder);if(!owned)throw new Error(`Welcome Funnel resume lock ownership lost for ${p.conversationId}`);};
 const stopHeartbeat=startAgentConversationLockHeartbeat({supabaseAdmin:p.supabaseAdmin,conversationId:p.conversationId,holder,onOwnershipLost:(error)=>{leaseError=error;}});
 try{await assertExecutionOwnership();const before=await classify(identity);if(before!=="durable_running")return before==="durable_completed"?{status:"already_completed",classification:before}:{status:"blocked",classification:before as any};
  const{data:armed,error:armError}=await p.supabaseAdmin.rpc("arm_recovered_welcome_funnel_execution",{p_funnel_id:p.funnel.id,p_contact_id:p.contactId,p_conversation_id:p.conversationId,p_user_id:p.userId,p_workspace_id:p.workspaceId,p_holder:holder});if(armError||armed!==true)throw new Error(`Welcome Funnel recovered resume was not armed: ${armError?.message||"refused"}`);
  await runWelcomeFunnelSequence({supabase:p.supabaseAdmin,funnel:p.funnel,contactId:p.contactId,conversationId:p.conversationId,userId:p.userId,workspaceId:p.workspaceId,phone:p.phone,creds:p.creds,initiatedBy:"resume",holder,assertExecutionOwnership,resumeAfterStep:null,skipExecutionStart:true});await assertExecutionOwnership();const terminal=await classify(identity);if(terminal!=="durable_completed")throw new Error(`Recovered Welcome Funnel returned without durable completion: ${terminal}`);return{status:"completed",classification:"durable_completed"};
 }finally{stopHeartbeat();await releaseAgentConversationLock(p.supabaseAdmin,p.conversationId,holder);}}

export type WelcomeFunnelOrchestrationResult=|{status:"completed";classification:"durable_completed"}|{status:"already_completed";classification:"durable_completed"}|{status:"historical_compatible";classification:"legacy_compatible"}|{status:"blocked";classification:"durable_running"|"durable_needs_review"|"durable_identity_mismatch"|"legacy_ambiguous"}|{status:"busy";classification:"unclaimed"};
async function classify(p:{supabaseAdmin:any;funnelId:string;contactId:string;conversationId:string;userId:string;workspaceId:string}){return classifyWelcomeFunnelExecution(p.supabaseAdmin,p.funnelId,p.contactId,p.conversationId,p.userId,p.workspaceId);}
async function quarantineLegacyAmbiguousClaim(p:{supabaseAdmin:any;funnelId:string;contactId:string;conversationId:string;userId:string;workspaceId:string;holder:string}){const{data,error}=await p.supabaseAdmin.rpc("quarantine_ambiguous_welcome_funnel_claim",{p_funnel_id:p.funnelId,p_contact_id:p.contactId,p_conversation_id:p.conversationId,p_user_id:p.userId,p_workspace_id:p.workspaceId,p_holder:p.holder});if(error)throw error;if(data!==true)throw new Error(`Ambiguous Welcome Funnel claim quarantine was not confirmed for ${p.funnelId}/${p.contactId}`);}
export async function orchestrateWelcomeFunnel(p:{supabaseAdmin:any;funnel:WelcomeFunnelRuntime;contactId:string;conversationId:string;userId:string;workspaceId:string;phone:string;creds:{uazapi_url:string;uazapi_token:string}}):Promise<WelcomeFunnelOrchestrationResult>{
 const identity={supabaseAdmin:p.supabaseAdmin,funnelId:p.funnel.id,contactId:p.contactId,conversationId:p.conversationId,userId:p.userId,workspaceId:p.workspaceId};
 // Durable execution state is the only runtime authority for a new trigger.
 // welcome_funnel_runs is a legacy claim table and must never be written before
 // classification/start: doing so turns a brand-new trigger into legacy_ambiguous
 // and quarantines it before the first Funnel step is sent.
 const initial=await classify(identity);
 if(initial==="durable_completed")return{status:"already_completed",classification:initial};if(initial==="legacy_compatible")return{status:"historical_compatible",classification:initial};if(initial!=="legacy_ambiguous"&&blocksAutomaticAgentAfterFunnelClassification(initial))return{status:"blocked",classification:initial};if(initial!=="legacy_ambiguous"&&!mayStartWelcomeFunnelExecution(initial))throw new Error(`Unhandled Welcome Funnel classification: ${initial}`);
 const holder=`welcome-funnel:${p.funnel.id}:${randomUUID()}`;const acquired=await acquireAgentConversationLock(p.supabaseAdmin,p.conversationId,holder);if(!acquired)return{status:"busy",classification:"unclaimed"};let leaseError:Error|null=null;
 const assertExecutionOwnership=async()=>{if(leaseError)throw leaseError;const owned=await refreshAgentConversationLock(p.supabaseAdmin,p.conversationId,holder);if(!owned)throw new Error(`Welcome Funnel conversation lock ownership lost for ${p.conversationId}`);if(leaseError)throw leaseError;};
 const stopHeartbeat=startAgentConversationLockHeartbeat({supabaseAdmin:p.supabaseAdmin,conversationId:p.conversationId,holder,onOwnershipLost:(error)=>{leaseError=error;}});
 try{await assertExecutionOwnership();const fenced=await classify(identity);if(fenced==="durable_completed")return{status:"already_completed",classification:fenced};if(fenced==="legacy_compatible")return{status:"historical_compatible",classification:fenced};if(fenced==="legacy_ambiguous"){await removeFreshLegacyClaimBeforeDurableStart({supabaseAdmin:p.supabaseAdmin,funnelId:p.funnel.id,contactId:p.contactId,userId:p.userId,workspaceId:p.workspaceId});const repaired=await classify(identity);if(repaired!=="unclaimed"){await quarantineLegacyAmbiguousClaim({supabaseAdmin:p.supabaseAdmin,funnelId:p.funnel.id,contactId:p.contactId,conversationId:p.conversationId,userId:p.userId,workspaceId:p.workspaceId,holder});const quarantined=await classify(identity);if(quarantined!=="durable_needs_review")throw new Error(`Ambiguous Welcome Funnel claim returned without durable review: ${quarantined}`);return{status:"blocked",classification:quarantined};} }if(blocksAutomaticAgentAfterFunnelClassification(fenced))return{status:"blocked",classification:fenced};if(!mayStartWelcomeFunnelExecution(fenced))throw new Error(`Unhandled fenced Welcome Funnel classification: ${fenced}`);
  await runWelcomeFunnelSequence({supabase:p.supabaseAdmin,funnel:p.funnel,contactId:p.contactId,conversationId:p.conversationId,userId:p.userId,workspaceId:p.workspaceId,phone:p.phone,creds:p.creds,initiatedBy:"trigger",holder,assertExecutionOwnership});await assertExecutionOwnership();const terminal=await classify(identity);if(terminal!=="durable_completed")throw new Error(`Welcome Funnel returned without durable completion: ${terminal}`);return{status:"completed",classification:"durable_completed"};
 }finally{stopHeartbeat();const released=await releaseAgentConversationLock(p.supabaseAdmin,p.conversationId,holder);if(!released)console.error("[WELCOME-FUNNEL] exact-holder generation lock release was not confirmed",{conversationId:p.conversationId,holder});}}
export function shouldBlockAgentForWelcomeFunnel(result:WelcomeFunnelOrchestrationResult):boolean{return result.status==="blocked"||result.status==="busy"||result.status==="completed";}
export function describeWelcomeFunnelClassification(value:WelcomeFunnelExecutionClass):string{return value;}
