import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";
const historical=readFileSync("supabase/migrations/20260914360000_stage_b_turn_member_status_invariant.sql","utf8");
const finalIdentity=readFileSync("supabase/migrations/20260914534500_customer_turn_member_user_routing_fence.sql","utf8");
describe("Customer Turn Stage B membership invariant",()=>{
 it("historically serializes attachment and requires an unclaimed pending exact Stage B job",()=>{expect(historical).toContain("pg_advisory_xact_lock(hashtextextended(v_conversation_id::text,31))");const fence=historical.indexOf("PERFORM pg_advisory_xact_lock");const authoritative=historical.indexOf("SELECT status,claimed_by",fence);expect(fence).toBeGreaterThan(0);expect(authoritative).toBeGreaterThan(fence);expect(historical).not.toContain("FOR UPDATE");expect(historical).toContain("id=NEW.job_id AND message_id=NEW.message_id AND conversation_id=v_conversation_id");expect(historical).toContain("v_status<>'pending' OR v_claimed_by IS NOT NULL");});
 it("final trigger revalidates exact Stage B identity under seed 31 with row ownership",()=>{expect(finalIdentity).toContain("pg_advisory_xact_lock(hashtextextended(v_conversation_id::text,31))");const fence=finalIdentity.indexOf("PERFORM pg_advisory_xact_lock");const authoritative=finalIdentity.indexOf("FROM public.agent_inbound_jobs j WHERE j.id=NEW.job_id FOR UPDATE",fence);expect(authoritative).toBeGreaterThan(fence);expect(finalIdentity).toContain("v_message_id IS DISTINCT FROM NEW.message_id");expect(finalIdentity).toContain("v_status IS DISTINCT FROM 'pending' OR v_claimed_by IS NOT NULL");});
 it("final trigger refuses cross-workspace/user turns and active or uncertain Funnel ownership",()=>{expect(finalIdentity).toContain("c.id=v_conversation_id AND c.workspace_id=v_workspace_id");expect(finalIdentity).toContain("IF NOT FOUND OR v_user_id IS NULL");expect(finalIdentity).toContain("v_turn_workspace_id IS DISTINCT FROM v_workspace_id");expect(finalIdentity).toContain("v_turn_user_id IS DISTINCT FROM v_user_id");expect(finalIdentity).toContain("s.workspace_id IS DISTINCT FROM v_workspace_id");expect(finalIdentity).toContain("s.user_id IS DISTINCT FROM v_user_id");expect(finalIdentity).toContain("s.status IN('running','needs_review')");});
 it("final trigger remains the service-role-only attachment guard",()=>{expect(finalIdentity).toContain("CREATE OR REPLACE FUNCTION public.guard_agent_customer_turn_member_pending_job()");expect(finalIdentity).toContain("REVOKE ALL ON FUNCTION public.guard_agent_customer_turn_member_pending_job() FROM PUBLIC,anon,authenticated");expect(finalIdentity).toContain("GRANT EXECUTE ON FUNCTION public.guard_agent_customer_turn_member_pending_job() TO service_role");});
});
