import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";
const historical=readFileSync("supabase/migrations/20260914294500_bound_pending_drain_per_conversation.sql","utf8");
const finalDrain=readFileSync("supabase/migrations/20260914530000_pending_attachment_workspace_quarantine.sql","utf8");
const finalBarrier=readFileSync("supabase/migrations/20260914543000_background_funnel_user_identity_barrier.sql","utf8");
describe("pending Stage B attachment runtime fence",()=>{
 it("historically revalidates incompatible owners under the shared conversation fence",()=>{const lock=historical.indexOf("pg_try_advisory_xact_lock(hashtextextended(v_conversation.conversation_id::text,31))");const stageB=historical.indexOf("active_job.status IN ('processing_safe','processing')",lock);const turns=historical.indexOf("active_turn.state IN ('retry_safe','processing_safe','processing')",lock);const generation=historical.indexOf("FROM public.agent_generation_locks generation_lock",lock);expect(lock).toBeGreaterThan(-1);expect(stageB).toBeGreaterThan(lock);expect(turns).toBeGreaterThan(stageB);expect(generation).toBeGreaterThan(turns);});
 it("final drain keeps catch-up globally and per-conversation bounded",()=>{expect(finalDrain).toContain("SELECT DISTINCT ON(j.conversation_id)");expect(finalDrain).toContain("LIMIT least(v_target*10,1000)");expect(finalDrain).toContain("v_per_conversation integer:=least(16,greatest(1,ceil(v_target::numeric/4)::integer))");expect(finalDrain).toContain("EXIT WHEN v_count>=v_target OR v_conversation_count>=v_per_conversation");expect(finalDrain).toContain("FOR UPDATE OF j SKIP LOCKED");});
 it("final drain rechecks Funnel, Stage B, Customer Turn and generation owners after seed-31 acquisition and per job",()=>{const lock=finalDrain.indexOf("pg_try_advisory_xact_lock(hashtextextended(v_conversation.conversation_id::text,31))");expect(lock).toBeGreaterThan(-1);expect(finalDrain.indexOf("public.has_welcome_funnel_agent_barrier(v_conversation.conversation_id,v_conversation.workspace_id)",lock)).toBeGreaterThan(lock);expect(finalDrain.indexOf("a.status IN('processing_safe','processing')",lock)).toBeGreaterThan(lock);expect(finalDrain.indexOf("t.state IN('retry_safe','processing_safe','processing')",lock)).toBeGreaterThan(lock);expect(finalDrain.indexOf("agent_generation_locks g",lock)).toBeGreaterThan(lock);expect(finalDrain).toContain("public.has_welcome_funnel_agent_barrier(v_job.conversation_id,v_job.workspace_id)");});
 it("final shared Funnel barrier resolves current user and fails closed on routing drift",()=>{expect(finalBarrier).toContain("SELECT c.user_id INTO v_user_id");expect(finalBarrier).toContain("IF NOT FOUND OR v_user_id IS NULL THEN RETURN true");expect(finalBarrier).toContain("s.workspace_id IS DISTINCT FROM p_workspace_id");expect(finalBarrier).toContain("s.user_id IS DISTINCT FROM v_user_id");expect(finalBarrier).toContain("s.status IN('running','needs_review')");});
 it("quarantines a corrupt collecting workspace without consuming the unattached durable job",()=>{expect(finalDrain).toContain("v_turn_workspace IS DISTINCT FROM v_job.workspace_id");expect(finalDrain).toContain("state='needs_review'");expect(finalDrain).toContain("attached Customer Turn routing identity mismatch");expect(finalDrain).toContain("v_turn:=NULL;v_turn_workspace:=NULL");});
});
