import { readFileSync } from "node:fs";import { describe,expect,it } from "vitest";
const route=readFileSync("src/routes/api/public/hooks/agent-inbound-recovery.ts","utf8");
const recovery=readFileSync("src/lib/agent-v3/inbound-recovery.server.ts","utf8");
const lock=readFileSync("src/lib/agent-v3/conversation-lock.server.ts","utf8");
const stageB=readFileSync("supabase/migrations/20260914541500_stage_b_recovery_ownership_separation.sql","utf8");
const generation=readFileSync("supabase/migrations/20260914450000_generation_lock_recovery_fairness_with_funnel.sql","utf8");
const funnel=readFileSync("supabase/migrations/20260914533000_welcome_funnel_recovery_full_identity.sql","utf8");
describe("durable recovery endpoint",()=>{
 it("authenticates before loading service-role client and exposes POST only",()=>{const auth=route.indexOf("assertCronAuthorized(request)");const admin=route.indexOf('await import("@/integrations/supabase/client.server")');expect(auth).toBeGreaterThan(-1);expect(admin).toBeGreaterThan(auth);expect(route).toContain("POST: async");expect(route).not.toContain("GET: async");});
 it("runs Stage B before generic generation recovery before Funnel-specific recovery",()=>{const a=route.indexOf("recoverAgentInboundDispatcherClaims(");const b=route.indexOf("recoverStaleAgentConversationLocks(",a);const c=route.indexOf('"recover_stale_welcome_funnel_executions"',b);expect(a).toBeGreaterThan(-1);expect(b).toBeGreaterThan(a);expect(c).toBeGreaterThan(b);expect(route).toContain("GENERATION_LOCK_STALE_MS = DB_CONVERSATION_LOCK_STALE_MS");expect(route).toContain("WELCOME_FUNNEL_STALE_MS = DB_CONVERSATION_LOCK_STALE_MS");});
 it("keeps recovery dependency graph effect-free",()=>{expect(recovery).toContain("recoverStaleAgentInboundJobs");expect(recovery).not.toContain("runtime.server");expect(route).not.toContain("executeAgentV3Runtime");expect(route).not.toContain("runAgentV3Turn");expect(lock).toContain('"recover_stale_agent_generation_locks"');});
 it("Stage B recovery never deletes generation ownership and quarantines post-runtime uncertainty",()=>{expect(stageB).toContain("LIMIT 500");expect(stageB).toContain("EXIT WHEN v_locked>=100");expect(stageB).toContain("status='pending'");expect(stageB).toContain("status='needs_review'");expect(stageB).not.toContain("DELETE FROM public.agent_generation_locks");});
 it("generic generation recovery is fair and refuses active durable owners including running Funnel",()=>{expect(generation).toContain("LIMIT 500");expect(generation).toContain("EXIT WHEN v_locked>=100");expect(generation).toContain("pg_try_advisory_xact_lock(hashtextextended(v_candidate.conversation_id::text,31))");expect(generation).toContain("active_job.status IN ('processing_safe','processing')");expect(generation).toContain("active_turn.state IN ('processing_safe','processing')");expect(generation).toContain("funnel.status='running'");});
 it("Funnel stale recovery uses full routing identity under the canonical lock horizon",()=>{expect(funnel).toContain("p_generation_lock_stale_before");expect(funnel).toContain("conversation_id");expect(funnel).toContain("user_id");expect(funnel).toContain("workspace_id");expect(funnel).toContain("needs_review");});
});
