import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const claimant=readFileSync("supabase/migrations/20260914511500_stage_b_claim_funnel_workspace_identity.sql","utf8");
const direct=readFileSync("supabase/migrations/20260914524500_stage_b_direct_claim_funnel_barrier.sql","utf8");
const finalBarrier=readFileSync("supabase/migrations/20260914543000_background_funnel_user_identity_barrier.sql","utf8");
describe("Stage B Funnel routing fence",()=>{
 it("uses shared routing barrier in exhausted and ordinary background scans",()=>{expect((claimant.match(/has_welcome_funnel_agent_barrier/g)||[]).length).toBeGreaterThanOrEqual(6);expect(claimant).toContain("j.workspace_id");});
 it("revalidates background claim after canonical nonblocking fence",()=>{const lock=claimant.indexOf("pg_try_advisory_xact_lock(hashtextextended(v_candidate.conversation_id::text,31))");expect(lock).toBeGreaterThan(0);expect(claimant.indexOf("has_welcome_funnel_agent_barrier(v_candidate.conversation_id,v_candidate.workspace_id)",lock)).toBeGreaterThan(lock);});
 it("keeps background and direct claims on the real max-attempt bound",()=>{for(const sql of [claimant,direct]){expect(sql).toContain("j.attempt_count>=p_max_attempts");expect(sql).toContain("j.attempt_count<p_max_attempts");expect(sql).not.toContain("2147483647");}});
 it("direct claim serializes and rechecks the same shared barrier before processing_safe",()=>{expect(direct).toContain("pg_advisory_xact_lock(hashtextextended(v_conversation_id::text,31))");expect(direct).toContain("public.has_welcome_funnel_agent_barrier(v_conversation_id,v_workspace_id)");expect(direct).toContain("NOT public.has_welcome_funnel_agent_barrier(j.conversation_id,j.workspace_id)");expect(direct).toContain("status='processing_safe'");});
 it("final shared barrier resolves current user and fails closed on missing or mismatched routing identity",()=>{expect(finalBarrier).toContain("SELECT c.user_id INTO v_user_id");expect(finalBarrier).toContain("IF NOT FOUND OR v_user_id IS NULL THEN RETURN true");expect(finalBarrier).toContain("s.workspace_id IS DISTINCT FROM p_workspace_id");expect(finalBarrier).toContain("s.user_id IS DISTINCT FROM v_user_id");expect(finalBarrier).toContain("s.status IN('running','needs_review')");});
});
