import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const sql=readFileSync("supabase/migrations/20260914524500_stage_b_direct_claim_funnel_barrier.sql","utf8");
const barrier=readFileSync("supabase/migrations/20260914543000_background_funnel_user_identity_barrier.sql","utf8");
describe("direct Stage B claim Funnel barrier",()=>{
 it("discovers durable routing and serializes on seed 31",()=>{expect(sql).toContain("SELECT conversation_id,workspace_id INTO v_conversation_id,v_workspace_id");expect(sql).toContain("pg_advisory_xact_lock(hashtextextended(v_conversation_id::text,31))");});
 it("fails closed behind the final shared Funnel user/workspace barrier",()=>{expect(sql).toContain("public.has_welcome_funnel_agent_barrier(v_conversation_id,v_workspace_id)");expect(sql).toContain("NOT public.has_welcome_funnel_agent_barrier(j.conversation_id,j.workspace_id)");expect(barrier).toContain("SELECT c.user_id INTO v_user_id");expect(barrier).toContain("IF NOT FOUND OR v_user_id IS NULL THEN RETURN true");expect(barrier).toContain("s.workspace_id IS DISTINCT FROM p_workspace_id");expect(barrier).toContain("s.user_id IS DISTINCT FROM v_user_id");expect(barrier).toContain("s.status IN('running','needs_review')");});
 it("does not claim across Customer Turn, attached membership, generation lock, or another Stage B runtime",()=>{expect(sql).toContain("agent_customer_turn_messages");expect(sql).toContain("t.state IN('processing_safe','processing')");expect(sql).toContain("active.status IN('processing_safe','processing')");expect(sql).toContain("g.conversation_id=v_conversation_id");});
 it("quarantines exhausted work and only enters processing_safe below the real attempt bound",()=>{expect(sql).toContain("j.attempt_count>=p_max_attempts");expect(sql).toContain("status='needs_review'");expect(sql).toContain("j.attempt_count<p_max_attempts");expect(sql).toContain("status='processing_safe'");expect(sql).not.toContain("2147483647");});
});
