import { readFileSync } from "node:fs";import { describe,expect,it } from "vitest";
const migration=readFileSync("supabase/migrations/20260914300000_unattached_review_blocks_customer_turn.sql","utf8");
const dispatcher=readFileSync("src/lib/agent-v3/customer-turn-dispatch.server.ts","utf8");
const finalBarrier=readFileSync("supabase/migrations/20260914543000_background_funnel_user_identity_barrier.sql","utf8");
describe("unattached needs_review semantic barrier",()=>{
 it("blocks collecting/retry claims behind unattached review jobs",()=>{expect(migration.match(/review_job\.status='needs_review'/g)?.length??0).toBeGreaterThanOrEqual(4);expect(migration).toContain("NOT EXISTS(SELECT 1 FROM public.agent_customer_turn_messages tm WHERE tm.job_id=review_job.id)");expect(migration).toContain("t.state='retry_safe'");});
 it("quarantines incomplete semantic turns under nonblocking seed31",()=>{expect(migration).toContain("quarantine_customer_turns_with_unattached_review");expect(migration).toContain("SET state='needs_review'");expect(migration).toContain("pg_try_advisory_xact_lock(hashtextextended(v_candidate.conversation_id::text,31))");});
 it("dispatcher runs attachment then review/snapshot quarantine before claims",()=>{const attach=dispatcher.indexOf("attachPendingAgentInboundJobsToCustomerTurns");const review=dispatcher.lastIndexOf("quarantineCustomerTurnsWithUnattachedReview");const snapshot=dispatcher.lastIndexOf("quarantineIncompleteCustomerTurnSnapshots");const loop=dispatcher.indexOf("for(let attempt=0");expect(attach).toBeGreaterThan(-1);expect(review).toBeGreaterThan(attach);expect(snapshot).toBeGreaterThan(review);expect(loop).toBeGreaterThan(snapshot);});
 it("final shared Funnel barrier additionally fails closed on current routing uncertainty",()=>{expect(finalBarrier).toContain("IF NOT FOUND OR v_user_id IS NULL THEN RETURN true");expect(finalBarrier).toContain("s.workspace_id IS DISTINCT FROM p_workspace_id");expect(finalBarrier).toContain("s.user_id IS DISTINCT FROM v_user_id");});
});
