import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";
const source=readFileSync("src/lib/welcome-funnel-runner.server.ts","utf8");
const historical=readFileSync("supabase/migrations/20260914433000_welcome_funnel_exact_holder_transitions.sql","utf8");
const finalMutation=readFileSync("supabase/migrations/20260914531500_welcome_funnel_mutation_full_identity_fence.sql","utf8");
const finalStart=readFileSync("supabase/migrations/20260914521500_welcome_funnel_start_primary_identity_fence.sql","utf8");
describe("Welcome Funnel durable progress",()=>{
 it("creates running state through the exact-holder RPC before any provider send",()=>{expect(source.indexOf("await startExecutionState")).toBeLessThan(source.indexOf("await uazapiSendText"));expect(source).toContain('rpc("start_welcome_funnel_execution"');expect(source).toContain("p_holder:params.holder");expect(source).not.toContain('.from("welcome_funnel_execution_state").insert(');});
 it("keeps the historical exact-holder checkpoint fence",()=>{expect(historical).toContain("hashtextextended(p_conversation_id::text, 31)");expect(historical).toContain("g.holder = p_holder");expect(historical).toContain("exact holder ownership was lost");});
 it("routes final checkpoints and terminal mutations through full durable routing identity",()=>{expect(source).toContain('rpc("mutate_welcome_funnel_execution"');expect(source).toContain("p_user_id:params.userId");expect(source).toContain("p_workspace_id:params.workspaceId");expect(finalMutation).toContain("g.conversation_id=p_conversation_id AND g.holder=p_holder");expect(finalMutation).toContain("v_user_id IS DISTINCT FROM p_user_id");expect(finalMutation).toContain("v_workspace_id IS DISTINCT FROM p_workspace_id");expect(finalMutation).toContain("conversation_id=p_conversation_id AND user_id=p_user_id AND workspace_id=p_workspace_id AND status='running'");expect(finalMutation).toContain("REVOKE ALL ON FUNCTION public.mutate_welcome_funnel_execution(uuid,uuid,uuid,text,text,text,text) FROM PUBLIC,anon,authenticated,service_role");});
 it("starts only under exact lock ownership and rejects durable primary/routing drift",()=>{expect(finalStart).toContain("conversation_id=p_conversation_id AND holder=p_holder");expect(finalStart).toContain("v_user_id IS DISTINCT FROM p_user_id");expect(finalStart).toContain("v_workspace_id IS DISTINCT FROM p_workspace_id");expect(finalStart).toContain("Welcome Funnel start blocked by durable primary identity mismatch");expect(finalStart).toContain("Welcome Funnel start blocked by conversation routing identity mismatch");});
 it("keeps CRM completion secondary to durable execution truth",()=>{expect(source.indexOf("await markExecutionCompleted")).toBeLessThan(source.indexOf('funnel_status:"completed"'));});
 it("does not let the ownerless compatibility failure logger mutate durable execution state",()=>{const marker=source.indexOf("export async function markFunnelRunFailed");expect(marker).toBeGreaterThan(-1);expect(source.slice(marker)).not.toContain('welcome_funnel_execution_state").update');expect(source.slice(marker)).toContain("não altera estado durável sem exact-holder");});
});
