import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";
const historical=readFileSync("supabase/migrations/20260914410000_welcome_funnel_start_runtime_fence.sql","utf8");
const finalStart=readFileSync("supabase/migrations/20260914521500_welcome_funnel_start_primary_identity_fence.sql","utf8");
describe("Welcome Funnel symmetric runtime fence",()=>{
 it("historically serializes start and rejects active Agent V3 owners",()=>{expect(historical).toContain("pg_advisory_xact_lock(hashtextextended(NEW.conversation_id::text,31))");expect(historical).toContain("agent_customer_turns");expect(historical).toContain("t.state IN ('processing_safe','processing')");expect(historical).toContain("agent_inbound_jobs");expect(historical).toContain("j.status IN ('processing_safe','processing')");expect(historical).toContain("BEFORE INSERT ON public.welcome_funnel_execution_state");});
 it("final start preserves symmetric runtime exclusion with exact generation ownership",()=>{expect(finalStart).toContain("pg_advisory_xact_lock(hashtextextended(p_conversation_id::text,31))");expect(finalStart).toContain("conversation_id=p_conversation_id AND holder=p_holder");expect(finalStart).toContain("agent_customer_turns WHERE conversation_id=p_conversation_id AND state IN('processing_safe','processing')");expect(finalStart).toContain("agent_inbound_jobs WHERE conversation_id=p_conversation_id AND status IN('processing_safe','processing')");});
 it("final start fails closed on durable and Agent routing identity drift",()=>{expect(finalStart).toContain("v_conversation_id IS DISTINCT FROM p_conversation_id");expect(finalStart).toContain("v_user_id IS DISTINCT FROM p_user_id");expect(finalStart).toContain("v_workspace_id IS DISTINCT FROM p_workspace_id");expect(finalStart).toContain("Welcome Funnel start blocked by conversation routing identity mismatch");expect(finalStart).toContain("Welcome Funnel start blocked by Agent routing identity mismatch");});
});
