import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const read=(p:string)=>readFileSync(p,"utf8");
const webhook=read("src/routes/api/public/hooks/uazapi-webhook.ts");const ingress=read("src/lib/agent-v3/customer-turn-ingress.server.ts");const dispatch=read("src/lib/agent-v3/customer-turn-dispatch.server.ts");const recovery=read("src/routes/api/public/hooks/agent-inbound-recovery.ts");const funnel=read("src/lib/welcome-funnel-orchestrator.server.ts");const locks=read("src/lib/agent-v3/conversation-lock.server.ts");
describe("Zero Lost Turn final cross-layer contract",()=>{
 it("webhook persists exact inbound ownership before semantic runtime",()=>{expect(webhook).toContain("enqueueWebhookInboundAroundWelcomeFunnel");const body=ingress.slice(ingress.indexOf("export async function enqueueAgentInboundIntoCustomerTurn"));const ensure=body.indexOf("await ensureAgentInboundJob");const attach=body.indexOf("await attachAgentInboundJobToCustomerTurn");expect(ensure).toBeGreaterThanOrEqual(0);expect(attach).toBeGreaterThan(ensure);});
 it("Customer Turn crosses processing boundary only after input construction",()=>{const body=dispatch.slice(dispatch.indexOf("async function executeClaimedCustomerTurn"),dispatch.indexOf("export async function dispatchReadyCustomerTurnById"));const build=body.indexOf("await buildCustomerTurnRuntimeInput");const enter=body.indexOf("await enterCustomerTurnRuntime");const execute=body.indexOf("await executeAgentV3Runtime");expect(build).toBeGreaterThanOrEqual(0);expect(enter).toBeGreaterThan(build);expect(execute).toBeGreaterThan(enter);expect(body).toContain("quarantineClaimedCustomerTurn");});
 it("Funnel owns exact generation lease and verifies durable completion",()=>{expect(funnel).toContain("acquireAgentConversationLock");expect(funnel).toContain("assertExecutionOwnership");expect(funnel).toContain('terminal!=="durable_completed"');});
 it("recovery shares the canonical Funnel/generation stale horizon and never replays uncertain Funnel runtime",()=>{expect(recovery).toContain("GENERATION_LOCK_STALE_MS = DB_CONVERSATION_LOCK_STALE_MS");expect(recovery).toContain("WELCOME_FUNNEL_STALE_MS = DB_CONVERSATION_LOCK_STALE_MS");expect(recovery).toContain("recover_stale_welcome_funnel_executions");});
 it("generation lock contract keeps canonical 20 minute horizon",()=>expect(locks).toContain("20 * 60 * 1000"));
});
