export const AGENT_INBOUND_MAX_SAFE_ATTEMPTS = 5;
export type AgentInboundKind = "texto" | "audio" | "image" | "sticker";
export type AgentInboundJob = { id:string; message_id:string; conversation_id:string; workspace_id:string; send_target:string; input_text:string; input_kind:AgentInboundKind; input_mime:string|null; deferred_funnel:boolean; status:"pending"|"processing_safe"|"processing"|"processed"|"needs_review"; claimed_by:string|null; claimed_at:string|null; attempt_count:number; last_error:string|null; created_at:string; updated_at:string };
export type EnsureAgentInboundJobInput = { messageId:string; conversationId:string; workspaceId:string; sendTarget:string; inputText:string; inputKind:AgentInboundKind; inputMime?:string; deferredFunnel:boolean };
export type EnsureAgentInboundJobResult = { job:AgentInboundJob; duplicate:boolean };
function sameInboundSnapshot(job:AgentInboundJob,input:EnsureAgentInboundJobInput):boolean{return job.message_id===input.messageId&&job.conversation_id===input.conversationId&&job.workspace_id===input.workspaceId&&job.send_target===input.sendTarget&&job.input_text===input.inputText&&job.input_kind===input.inputKind&&(job.input_mime??null)===(input.inputMime??null)&&job.deferred_funnel===input.deferredFunnel;}
function validateInboundSnapshot(input:EnsureAgentInboundJobInput):void{if(!input.messageId?.trim())throw new Error("Agent inbound message identity is missing");if(!input.conversationId?.trim())throw new Error(`Agent inbound conversation identity is missing for message ${input.messageId}`);if(!input.workspaceId?.trim())throw new Error(`Agent inbound workspace identity is missing for message ${input.messageId}`);if(!input.sendTarget?.trim())throw new Error(`Agent inbound send target is missing for message ${input.messageId}`);if(!["texto","audio","image","sticker"].includes(input.inputKind))throw new Error(`Agent inbound kind is invalid for message ${input.messageId}`);}
async function readAgentInboundJob(s:any,messageId:string):Promise<AgentInboundJob|null>{const{data,error}=await s.from("agent_inbound_jobs").select("*").eq("message_id",messageId).maybeSingle();if(error)throw error;return data?data as AgentInboundJob:null;}
/** The persisted CRM message is the canonical semantic payload for every Stage B job.
 * Never allow a webhook-local queued/deferred body to be paired with another
 * message_id. This closes the identity split even before the legacy webhook path
 * is removed. `deferred_funnel` is scheduling history, not payload identity, so
 * once the durable message is resolved it is normalized away. */
async function canonicalizeInboundMessageSnapshot(s:any,input:EnsureAgentInboundJobInput):Promise<EnsureAgentInboundJobInput>{const{data,error}=await s.from("messages").select("body,workspace_id,conversation_id").eq("id",input.messageId).eq("conversation_id",input.conversationId).eq("workspace_id",input.workspaceId).maybeSingle();if(error)throw error;if(!data)throw new Error(`Agent inbound message ${input.messageId} is missing or crossed its durable conversation/workspace identity`);if(data.workspace_id!==input.workspaceId||data.conversation_id!==input.conversationId)throw new Error(`Agent inbound message ${input.messageId} durable identity drifted`);return{...input,inputText:String(data.body??""),deferredFunnel:false};}
function unexpectedTransitionState(operation:string,messageId:string,current:AgentInboundJob|null):Error{const state=current?`${current.status}/${current.claimed_by??"unclaimed"}`:"missing";return new Error(`Agent inbound ${operation} is uncertain for message ${messageId}; durable state is ${state}`);}
export async function ensureAgentInboundJob(s:any,input:EnsureAgentInboundJobInput):Promise<EnsureAgentInboundJobResult>{validateInboundSnapshot(input);const canonicalInput=await canonicalizeInboundMessageSnapshot(s,input);validateInboundSnapshot(canonicalInput);const{data,error}=await s.from("agent_inbound_jobs").insert({message_id:canonicalInput.messageId,conversation_id:canonicalInput.conversationId,workspace_id:canonicalInput.workspaceId,send_target:canonicalInput.sendTarget,input_text:canonicalInput.inputText,input_kind:canonicalInput.inputKind,input_mime:canonicalInput.inputMime??null,deferred_funnel:canonicalInput.deferredFunnel,status:"pending"}).select("*").single();if(!error&&data)return{job:data as AgentInboundJob,duplicate:false};if(error?.code!=="23505")throw error??new Error(`Agent inbound job insert returned no row for message ${canonicalInput.messageId}`);const existing=await readAgentInboundJob(s,canonicalInput.messageId);if(!existing)throw new Error(`Agent inbound job duplicate disappeared for message ${canonicalInput.messageId}`);if(!sameInboundSnapshot(existing,canonicalInput))throw new Error(`Agent inbound job snapshot conflict for message ${canonicalInput.messageId}`);return{job:existing,duplicate:true};}
export async function claimAgentInboundJob(s:any,messageId:string,holder:string,maxAttempts=AGENT_INBOUND_MAX_SAFE_ATTEMPTS):Promise<boolean>{const{data,error}=await s.rpc("claim_agent_inbound_job",{p_message_id:messageId,p_holder:holder,p_max_attempts:maxAttempts});if(error)throw error;return data===true;}
export async function claimNextAgentInboundJob(s:any,holder:string,maxAttempts=AGENT_INBOUND_MAX_SAFE_ATTEMPTS):Promise<AgentInboundJob|null>{const{data,error}=await s.rpc("claim_next_agent_inbound_job_fenced",{p_holder:holder,p_max_attempts:maxAttempts});if(error)throw error;return Array.isArray(data)&&data.length>0?data[0] as AgentInboundJob:null;}
export async function transferAgentInboundJobClaim(s:any,messageId:string,fromHolder:string,toHolder:string):Promise<boolean>{const{data,error}=await s.rpc("transfer_agent_inbound_job_claim",{p_message_id:messageId,p_from_holder:fromHolder,p_to_holder:toHolder});if(!error&&data===true)return true;let current:AgentInboundJob|null=null;try{current=await readAgentInboundJob(s,messageId);if(current?.status==="processing_safe"&&current.claimed_by===toHolder)return true;if(current?.status==="processing_safe"&&current.claimed_by===fromHolder)return false;}catch(e){if(error)throw error;throw e;}if(error)throw error;throw unexpectedTransitionState("claim transfer",messageId,current);}
export async function enterAgentInboundRuntime(s:any,messageId:string,holder:string):Promise<boolean>{const{data,error}=await s.rpc("enter_agent_inbound_runtime",{p_message_id:messageId,p_holder:holder});if(!error&&data===true)return true;const current=await readAgentInboundJob(s,messageId);if(current?.status==="processing"&&current.claimed_by===holder)return true;if(current?.status==="processing_safe"&&current.claimed_by===holder)return false;if(error)throw error;throw unexpectedTransitionState("runtime transition",messageId,current);}
async function resolveBooleanTransition(s:any,rpc:string,args:Record<string,unknown>,messageId:string,operation:string,success:(current:AgentInboundJob)=>boolean,stillOwned:(current:AgentInboundJob)=>boolean):Promise<boolean>{const{data,error}=await s.rpc(rpc,args);if(!error&&data===true)return true;const current=await readAgentInboundJob(s,messageId);if(current&&success(current))return true;if(current&&stillOwned(current))return false;if(error)throw error;throw unexpectedTransitionState(operation,messageId,current);}
export async function releaseAgentInboundJob(s:any,messageId:string,holder:string,lastError?:string):Promise<boolean>{return resolveBooleanTransition(s,"release_agent_inbound_job_safe",{p_message_id:messageId,p_holder:holder,p_last_error:lastError??null},messageId,"safe requeue",current=>current.status==="pending"&&current.claimed_by===null,current=>current.status==="processing_safe"&&current.claimed_by===holder);}
export async function reviewSafeAgentInboundJob(s:any,messageId:string,holder:string,lastError:string):Promise<boolean>{return resolveBooleanTransition(s,"review_agent_inbound_job_safe",{p_message_id:messageId,p_holder:holder,p_last_error:lastError.slice(0,1000)},messageId,"safe review transition",current=>current.status==="needs_review"&&current.claimed_by===null,current=>current.status==="processing_safe"&&current.claimed_by===holder);}
export async function completeAgentInboundJob(s:any,messageId:string,holder:string):Promise<void>{const ok=await resolveBooleanTransition(s,"complete_agent_inbound_job",{p_message_id:messageId,p_holder:holder},messageId,"completion",current=>current.status==="processed"&&current.claimed_by===null,current=>current.status==="processing"&&current.claimed_by===holder);if(!ok)throw unexpectedTransitionState("completion",messageId,await readAgentInboundJob(s,messageId));}
export async function reviewAgentInboundJob(s:any,messageId:string,holder:string,lastError:string):Promise<boolean>{return resolveBooleanTransition(s,"review_agent_inbound_job_runtime",{p_message_id:messageId,p_holder:holder,p_last_error:lastError.slice(0,1000)},messageId,"runtime review transition",current=>current.status==="needs_review"&&current.claimed_by===null,current=>current.status==="processing"&&current.claimed_by===holder);}
export async function recoverStaleAgentInboundJobs(s:any,staleBefore:string,maxAttempts=AGENT_INBOUND_MAX_SAFE_ATTEMPTS):Promise<{requeued:number;review:number}>{const{data,error}=await s.rpc("recover_stale_agent_inbound_jobs",{p_stale_before:staleBefore,p_max_attempts:maxAttempts});if(error)throw error;const row=Array.isArray(data)?data[0]:data;return{requeued:Number(row?.requeued??0),review:Number(row?.review??0)};}
