export const AGENT_INBOUND_MAX_SAFE_ATTEMPTS = 5;
export type AgentInboundKind = "texto" | "audio" | "image" | "sticker";
export type AgentInboundJob = { id:string; message_id:string; conversation_id:string; workspace_id:string; send_target:string; input_text:string; input_kind:AgentInboundKind; input_mime:string|null; deferred_funnel:boolean; status:"pending"|"processing_safe"|"processing"|"processed"|"needs_review"; claimed_by:string|null; claimed_at:string|null; attempt_count:number; last_error:string|null; created_at:string; updated_at:string };
export type EnsureAgentInboundJobInput = { messageId:string; conversationId:string; workspaceId:string; sendTarget:string; inputText:string; inputKind:AgentInboundKind; inputMime?:string; deferredFunnel:boolean };
export type EnsureAgentInboundJobResult = { job:AgentInboundJob; duplicate:boolean };
function sameInboundSnapshot(job:AgentInboundJob,input:EnsureAgentInboundJobInput):boolean{return job.message_id===input.messageId&&job.conversation_id===input.conversationId&&job.workspace_id===input.workspaceId&&job.send_target===input.sendTarget&&job.input_text===input.inputText&&job.input_kind===input.inputKind&&(job.input_mime??null)===(input.inputMime??null)&&job.deferred_funnel===input.deferredFunnel;}
async function readAgentInboundJob(s:any,messageId:string):Promise<AgentInboundJob|null>{const{data,error}=await s.from("agent_inbound_jobs").select("*").eq("message_id",messageId).maybeSingle();if(error)throw error;return data?data as AgentInboundJob:null;}
function unexpectedTransitionState(operation:string,messageId:string,current:AgentInboundJob|null):Error{const state=current?`${current.status}/${current.claimed_by??"unclaimed"}`:"missing";return new Error(`Agent inbound ${operation} is uncertain for message ${messageId}; durable state is ${state}`);}
export async function ensureAgentInboundJob(s:any,input:EnsureAgentInboundJobInput):Promise<EnsureAgentInboundJobResult>{const{data,error}=await s.from("agent_inbound_jobs").insert({message_id:input.messageId,conversation_id:input.conversationId,workspace_id:input.workspaceId,send_target:input.sendTarget,input_text:input.inputText,input_kind:input.inputKind,input_mime:input.inputMime??null,deferred_funnel:input.deferredFunnel,status:"pending"}).select("*").single();if(!error&&data)return{job:data as AgentInboundJob,duplicate:false};if(error?.code!=="23505")throw error??new Error(`Agent inbound job insert returned no row for message ${input.messageId}`);const existing=await readAgentInboundJob(s,input.messageId);if(!existing)throw new Error(`Agent inbound job duplicate disappeared for message ${input.messageId}`);if(!sameInboundSnapshot(existing,input))throw new Error(`Agent inbound job snapshot conflict for message ${input.messageId}`);return{job:existing,duplicate:true};}
export async function claimAgentInboundJob(s:any,messageId:string,holder:string,maxAttempts=AGENT_INBOUND_MAX_SAFE_ATTEMPTS):Promise<boolean>{const{data,error}=await s.rpc("claim_agent_inbound_job",{p_message_id:messageId,p_holder:holder,p_max_attempts:maxAttempts});if(error)throw error;return data===true;}
export async function claimNextAgentInboundJob(s:any,holder:string,maxAttempts=AGENT_INBOUND_MAX_SAFE_ATTEMPTS):Promise<AgentInboundJob|null>{const{data,error}=await s.rpc("claim_next_agent_inbound_job",{p_holder:holder,p_max_attempts:maxAttempts});if(error)throw error;return Array.isArray(data)&&data.length>0?data[0] as AgentInboundJob:null;}
export async function transferAgentInboundJobClaim(s:any,messageId:string,fromHolder:string,toHolder:string):Promise<boolean>{const{data,error}=await s.rpc("transfer_agent_inbound_job_claim",{p_message_id:messageId,p_from_holder:fromHolder,p_to_holder:toHolder});if(!error&&data===true)return true;let current:AgentInboundJob|null=null;try{current=await readAgentInboundJob(s,messageId);if(current?.status==="processing_safe"&&current.claimed_by===toHolder)return true;if(current?.status==="processing_safe"&&current.claimed_by===fromHolder)return false;}catch(e){if(error)throw error;throw e;}if(error)throw error;throw unexpectedTransitionState("claim transfer",messageId,current);}
export async function enterAgentInboundRuntime(s:any,messageId:string,holder:string):Promise<boolean>{const{data,error}=await s.rpc("enter_agent_inbound_runtime",{p_message_id:messageId,p_holder:holder});if(!error&&data===true)return true;const current=await readAgentInboundJob(s,messageId);if(current?.status==="processing"&&current.claimed_by===holder)return true;if(current?.status==="processing_safe"&&current.claimed_by===holder)return false;if(error)throw error;throw unexpectedTransitionState("runtime transition",messageId,current);}
export async function releaseAgentInboundJob(s:any,messageId:string,holder:string,lastError?:string):Promise<boolean>{const{data,error}=await s.from("agent_inbound_jobs").update({status:"pending",claimed_by:null,claimed_at:null,last_error:lastError??null,updated_at:new Date().toISOString()}).eq("message_id",messageId).eq("status","processing_safe").eq("claimed_by",holder).select("id").maybeSingle();if(!error&&data?.id)return true;const current=await readAgentInboundJob(s,messageId);if(current?.status==="pending"&&current.claimed_by===null)return true;if(current?.status==="processing_safe"&&current.claimed_by===holder)return false;if(error)throw error;throw unexpectedTransitionState("safe requeue",messageId,current);}
export async function reviewSafeAgentInboundJob(s:any,messageId:string,holder:string,lastError:string):Promise<boolean>{const{data,error}=await s.from("agent_inbound_jobs").update({status:"needs_review",claimed_by:null,claimed_at:null,last_error:lastError.slice(0,1000),updated_at:new Date().toISOString()}).eq("message_id",messageId).eq("status","processing_safe").eq("claimed_by",holder).select("id").maybeSingle();if(!error&&data?.id)return true;const current=await readAgentInboundJob(s,messageId);if(current?.status==="needs_review"&&current.claimed_by===null)return true;if(current?.status==="processing_safe"&&current.claimed_by===holder)return false;if(error)throw error;throw unexpectedTransitionState("safe review transition",messageId,current);}
export async function completeAgentInboundJob(s:any,messageId:string,holder:string):Promise<void>{const{data,error}=await s.from("agent_inbound_jobs").update({status:"processed",claimed_by:null,claimed_at:null,last_error:null,updated_at:new Date().toISOString()}).eq("message_id",messageId).eq("status","processing").eq("claimed_by",holder).select("id").maybeSingle();if(!error&&data?.id)return;const current=await readAgentInboundJob(s,messageId);if(current?.status==="processed"&&current.claimed_by===null)return;if(error)throw error;throw unexpectedTransitionState("completion",messageId,current);}
export async function reviewAgentInboundJob(s:any,messageId:string,holder:string,lastError:string):Promise<boolean>{const{data,error}=await s.from("agent_inbound_jobs").update({status:"needs_review",claimed_by:null,claimed_at:null,last_error:lastError.slice(0,1000),updated_at:new Date().toISOString()}).eq("message_id",messageId).eq("status","processing").eq("claimed_by",holder).select("id").maybeSingle();if(!error&&data?.id)return true;const current=await readAgentInboundJob(s,messageId);if(current?.status==="needs_review"&&current.claimed_by===null)return true;if(current?.status==="processing"&&current.claimed_by===holder)return false;if(error)throw error;throw unexpectedTransitionState("runtime review transition",messageId,current);}
export async function recoverStaleAgentInboundJobs(s:any,staleBefore:string,maxAttempts=AGENT_INBOUND_MAX_SAFE_ATTEMPTS):Promise<{requeued:number;review:number}>{const{data,error}=await s.rpc("recover_stale_agent_inbound_jobs",{p_stale_before:staleBefore,p_max_attempts:maxAttempts});if(error)throw error;const row=Array.isArray(data)?data[0]:data;return{requeued:Number(row?.requeued??0),review:Number(row?.review??0)};}
