/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTesteGratisRouteImport } from './routes/_authenticated/teste-gratis'
import { Route as AuthenticatedNumerosRouteImport } from './routes/_authenticated/numeros'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedDisparosRouteImport } from './routes/_authenticated/disparos'
import { Route as AuthenticatedConversasRouteImport } from './routes/_authenticated/conversas'
import { Route as AuthenticatedContatosRouteImport } from './routes/_authenticated/contatos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAgenteRouteImport } from './routes/_authenticated/agente'
import { Route as ApiPublicHooksUazapiWebhookRouteImport } from './routes/api/public/hooks/uazapi-webhook'
import { Route as ApiPublicHooksSmmPollRouteImport } from './routes/api/public/hooks/smm-poll'
import { Route as ApiPublicHooksCampaignDispatcherRouteImport } from './routes/api/public/hooks/campaign-dispatcher'
import { Route as ApiPublicHooksBlastDispatcherRouteImport } from './routes/api/public/hooks/blast-dispatcher'
import { Route as ApiPublicHooksAutoCampaignDispatcherRouteImport } from './routes/api/public/hooks/auto-campaign-dispatcher'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTesteGratisRoute =
  AuthenticatedTesteGratisRouteImport.update({
    id: '/teste-gratis',
    path: '/teste-gratis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNumerosRoute = AuthenticatedNumerosRouteImport.update({
  id: '/numeros',
  path: '/numeros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisparosRoute = AuthenticatedDisparosRouteImport.update({
  id: '/disparos',
  path: '/disparos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversasRoute = AuthenticatedConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContatosRoute = AuthenticatedContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenteRoute = AuthenticatedAgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksUazapiWebhookRoute =
  ApiPublicHooksUazapiWebhookRouteImport.update({
    id: '/api/public/hooks/uazapi-webhook',
    path: '/api/public/hooks/uazapi-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSmmPollRoute = ApiPublicHooksSmmPollRouteImport.update({
  id: '/api/public/hooks/smm-poll',
  path: '/api/public/hooks/smm-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCampaignDispatcherRoute =
  ApiPublicHooksCampaignDispatcherRouteImport.update({
    id: '/api/public/hooks/campaign-dispatcher',
    path: '/api/public/hooks/campaign-dispatcher',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBlastDispatcherRoute =
  ApiPublicHooksBlastDispatcherRouteImport.update({
    id: '/api/public/hooks/blast-dispatcher',
    path: '/api/public/hooks/blast-dispatcher',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoCampaignDispatcherRoute =
  ApiPublicHooksAutoCampaignDispatcherRouteImport.update({
    id: '/api/public/hooks/auto-campaign-dispatcher',
    path: '/api/public/hooks/auto-campaign-dispatcher',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agente': typeof AuthenticatedAgenteRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/disparos': typeof AuthenticatedDisparosRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/numeros': typeof AuthenticatedNumerosRoute
  '/teste-gratis': typeof AuthenticatedTesteGratisRoute
  '/api/public/hooks/auto-campaign-dispatcher': typeof ApiPublicHooksAutoCampaignDispatcherRoute
  '/api/public/hooks/blast-dispatcher': typeof ApiPublicHooksBlastDispatcherRoute
  '/api/public/hooks/campaign-dispatcher': typeof ApiPublicHooksCampaignDispatcherRoute
  '/api/public/hooks/smm-poll': typeof ApiPublicHooksSmmPollRoute
  '/api/public/hooks/uazapi-webhook': typeof ApiPublicHooksUazapiWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agente': typeof AuthenticatedAgenteRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/disparos': typeof AuthenticatedDisparosRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/numeros': typeof AuthenticatedNumerosRoute
  '/teste-gratis': typeof AuthenticatedTesteGratisRoute
  '/api/public/hooks/auto-campaign-dispatcher': typeof ApiPublicHooksAutoCampaignDispatcherRoute
  '/api/public/hooks/blast-dispatcher': typeof ApiPublicHooksBlastDispatcherRoute
  '/api/public/hooks/campaign-dispatcher': typeof ApiPublicHooksCampaignDispatcherRoute
  '/api/public/hooks/smm-poll': typeof ApiPublicHooksSmmPollRoute
  '/api/public/hooks/uazapi-webhook': typeof ApiPublicHooksUazapiWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agente': typeof AuthenticatedAgenteRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contatos': typeof AuthenticatedContatosRoute
  '/_authenticated/conversas': typeof AuthenticatedConversasRoute
  '/_authenticated/disparos': typeof AuthenticatedDisparosRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/numeros': typeof AuthenticatedNumerosRoute
  '/_authenticated/teste-gratis': typeof AuthenticatedTesteGratisRoute
  '/api/public/hooks/auto-campaign-dispatcher': typeof ApiPublicHooksAutoCampaignDispatcherRoute
  '/api/public/hooks/blast-dispatcher': typeof ApiPublicHooksBlastDispatcherRoute
  '/api/public/hooks/campaign-dispatcher': typeof ApiPublicHooksCampaignDispatcherRoute
  '/api/public/hooks/smm-poll': typeof ApiPublicHooksSmmPollRoute
  '/api/public/hooks/uazapi-webhook': typeof ApiPublicHooksUazapiWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agente'
    | '/configuracoes'
    | '/contatos'
    | '/conversas'
    | '/disparos'
    | '/logs'
    | '/numeros'
    | '/teste-gratis'
    | '/api/public/hooks/auto-campaign-dispatcher'
    | '/api/public/hooks/blast-dispatcher'
    | '/api/public/hooks/campaign-dispatcher'
    | '/api/public/hooks/smm-poll'
    | '/api/public/hooks/uazapi-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agente'
    | '/configuracoes'
    | '/contatos'
    | '/conversas'
    | '/disparos'
    | '/logs'
    | '/numeros'
    | '/teste-gratis'
    | '/api/public/hooks/auto-campaign-dispatcher'
    | '/api/public/hooks/blast-dispatcher'
    | '/api/public/hooks/campaign-dispatcher'
    | '/api/public/hooks/smm-poll'
    | '/api/public/hooks/uazapi-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agente'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contatos'
    | '/_authenticated/conversas'
    | '/_authenticated/disparos'
    | '/_authenticated/logs'
    | '/_authenticated/numeros'
    | '/_authenticated/teste-gratis'
    | '/api/public/hooks/auto-campaign-dispatcher'
    | '/api/public/hooks/blast-dispatcher'
    | '/api/public/hooks/campaign-dispatcher'
    | '/api/public/hooks/smm-poll'
    | '/api/public/hooks/uazapi-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksAutoCampaignDispatcherRoute: typeof ApiPublicHooksAutoCampaignDispatcherRoute
  ApiPublicHooksBlastDispatcherRoute: typeof ApiPublicHooksBlastDispatcherRoute
  ApiPublicHooksCampaignDispatcherRoute: typeof ApiPublicHooksCampaignDispatcherRoute
  ApiPublicHooksSmmPollRoute: typeof ApiPublicHooksSmmPollRoute
  ApiPublicHooksUazapiWebhookRoute: typeof ApiPublicHooksUazapiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teste-gratis': {
      id: '/_authenticated/teste-gratis'
      path: '/teste-gratis'
      fullPath: '/teste-gratis'
      preLoaderRoute: typeof AuthenticatedTesteGratisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/numeros': {
      id: '/_authenticated/numeros'
      path: '/numeros'
      fullPath: '/numeros'
      preLoaderRoute: typeof AuthenticatedNumerosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disparos': {
      id: '/_authenticated/disparos'
      path: '/disparos'
      fullPath: '/disparos'
      preLoaderRoute: typeof AuthenticatedDisparosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversas': {
      id: '/_authenticated/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof AuthenticatedConversasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contatos': {
      id: '/_authenticated/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AuthenticatedContatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agente': {
      id: '/_authenticated/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AuthenticatedAgenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/uazapi-webhook': {
      id: '/api/public/hooks/uazapi-webhook'
      path: '/api/public/hooks/uazapi-webhook'
      fullPath: '/api/public/hooks/uazapi-webhook'
      preLoaderRoute: typeof ApiPublicHooksUazapiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/smm-poll': {
      id: '/api/public/hooks/smm-poll'
      path: '/api/public/hooks/smm-poll'
      fullPath: '/api/public/hooks/smm-poll'
      preLoaderRoute: typeof ApiPublicHooksSmmPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/campaign-dispatcher': {
      id: '/api/public/hooks/campaign-dispatcher'
      path: '/api/public/hooks/campaign-dispatcher'
      fullPath: '/api/public/hooks/campaign-dispatcher'
      preLoaderRoute: typeof ApiPublicHooksCampaignDispatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/blast-dispatcher': {
      id: '/api/public/hooks/blast-dispatcher'
      path: '/api/public/hooks/blast-dispatcher'
      fullPath: '/api/public/hooks/blast-dispatcher'
      preLoaderRoute: typeof ApiPublicHooksBlastDispatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-campaign-dispatcher': {
      id: '/api/public/hooks/auto-campaign-dispatcher'
      path: '/api/public/hooks/auto-campaign-dispatcher'
      fullPath: '/api/public/hooks/auto-campaign-dispatcher'
      preLoaderRoute: typeof ApiPublicHooksAutoCampaignDispatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgenteRoute: typeof AuthenticatedAgenteRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContatosRoute: typeof AuthenticatedContatosRoute
  AuthenticatedConversasRoute: typeof AuthenticatedConversasRoute
  AuthenticatedDisparosRoute: typeof AuthenticatedDisparosRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedNumerosRoute: typeof AuthenticatedNumerosRoute
  AuthenticatedTesteGratisRoute: typeof AuthenticatedTesteGratisRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgenteRoute: AuthenticatedAgenteRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContatosRoute: AuthenticatedContatosRoute,
  AuthenticatedConversasRoute: AuthenticatedConversasRoute,
  AuthenticatedDisparosRoute: AuthenticatedDisparosRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedNumerosRoute: AuthenticatedNumerosRoute,
  AuthenticatedTesteGratisRoute: AuthenticatedTesteGratisRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksAutoCampaignDispatcherRoute:
    ApiPublicHooksAutoCampaignDispatcherRoute,
  ApiPublicHooksBlastDispatcherRoute: ApiPublicHooksBlastDispatcherRoute,
  ApiPublicHooksCampaignDispatcherRoute: ApiPublicHooksCampaignDispatcherRoute,
  ApiPublicHooksSmmPollRoute: ApiPublicHooksSmmPollRoute,
  ApiPublicHooksUazapiWebhookRoute: ApiPublicHooksUazapiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
