-- Restores the append-only Welcome Funnel observability sink used by
-- welcome-funnel-runner.server.ts. Runtime behavior does not depend on this
-- table; logging remains fail-open.
create table if not exists public.welcome_funnel_run_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  workspace_id uuid not null,
  funnel_id uuid not null,
  contact_id uuid not null,
  event_type text not null,
  step_key text null,
  message text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists welcome_funnel_run_events_funnel_contact_created_idx
  on public.welcome_funnel_run_events (funnel_id, contact_id, created_at desc);

create index if not exists welcome_funnel_run_events_workspace_created_idx
  on public.welcome_funnel_run_events (workspace_id, created_at desc);

alter table public.welcome_funnel_run_events enable row level security;
