-- Allow only the explicitly validated Welcome Funnel recovery path to restore
-- its own generation lock while preserving the global running-funnel fence.
--
-- The capability is transaction-local and bound to the exact conversation
-- and holder generated by acquire_recovered_welcome_funnel_lock().
-- Ordinary Agent V3 / legacy lock acquisition remains blocked whenever a
-- Welcome Funnel durably owns the conversation.

CREATE OR REPLACE FUNCTION public.guard_agent_generation_lock_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public AS $$
DECLARE
 v_recovery_conversation text :=
   current_setting('welcome_funnel.recovery_lock_conversation_id', true);
 v_recovery_holder text :=
   current_setting('welcome_funnel.recovery_lock_holder', true);
BEGIN
 PERFORM pg_advisory_xact_lock(
   hashtextextended(NEW.conversation_id::text,31)
 );

 -- Customer Turn ownership is never bypassed, including Funnel recovery.
 IF EXISTS(
  SELECT 1
  FROM public.agent_customer_turns t
  WHERE t.conversation_id=NEW.conversation_id
    AND t.state IN ('processing_safe','processing')
 ) THEN
  RAISE EXCEPTION
    'cannot acquire generation lock while customer turn owns conversation %',
    NEW.conversation_id
    USING ERRCODE='55000';
 END IF;

 IF EXISTS(
  SELECT 1
  FROM public.welcome_funnel_execution_state f
  WHERE f.conversation_id=NEW.conversation_id
    AND f.status='running'
 ) THEN

  -- Narrow exception: only the recovery RPC may set these transaction-local
  -- values, and both conversation and exact random holder must match.
  IF v_recovery_conversation=NEW.conversation_id::text
     AND v_recovery_holder=NEW.holder THEN
    RETURN NEW;
  END IF;

  RAISE EXCEPTION
    'cannot acquire generation lock while Welcome Funnel owns conversation %',
    NEW.conversation_id
    USING ERRCODE='55000';
 END IF;

 RETURN NEW;
END;
$$;

REVOKE ALL
ON FUNCTION public.guard_agent_generation_lock_insert()
FROM PUBLIC,anon,authenticated;

GRANT EXECUTE
ON FUNCTION public.guard_agent_generation_lock_insert()
TO service_role;


CREATE OR REPLACE FUNCTION public.acquire_recovered_welcome_funnel_lock(
 p_funnel_id uuid,
 p_contact_id uuid,
 p_conversation_id uuid,
 p_user_id uuid,
 p_workspace_id uuid,
 p_holder text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path='public','pg_temp'
AS $$
BEGIN
 IF p_holder IS NULL OR btrim(p_holder)='' THEN
  RETURN false;
 END IF;

 PERFORM pg_advisory_xact_lock(
   hashtextextended(p_conversation_id::text,31)
 );

 -- Never replace or overlap an existing generation owner.
 IF EXISTS(
  SELECT 1
  FROM public.agent_generation_locks
  WHERE conversation_id=p_conversation_id
 ) THEN
  RETURN false;
 END IF;

 -- Recovery cannot overlap inbound processing or a Customer Turn.
 IF EXISTS(
  SELECT 1
  FROM public.agent_inbound_jobs
  WHERE conversation_id=p_conversation_id
    AND status IN ('processing_safe','processing')
 )
 OR EXISTS(
  SELECT 1
  FROM public.agent_customer_turns
  WHERE conversation_id=p_conversation_id
    AND state IN ('processing_safe','processing')
 ) THEN
  RETURN false;
 END IF;

 -- Exact zero-effect recovered Funnel identity is mandatory.
 IF NOT EXISTS(
  SELECT 1
  FROM public.welcome_funnel_execution_state f
  WHERE f.funnel_id=p_funnel_id
    AND f.contact_id=p_contact_id
    AND f.conversation_id=p_conversation_id
    AND f.user_id=p_user_id
    AND f.workspace_id=p_workspace_id
    AND f.status='running'
    AND f.last_completed_step IS NULL
    AND NOT EXISTS(
      SELECT 1
      FROM public.messages m
      WHERE m.conversation_id=p_conversation_id
        AND m.sender='agente'
        AND m.created_at >= f.started_at - interval '2 minutes'
    )
 ) THEN
  RETURN false;
 END IF;

 -- Transaction-local exact-holder capability consumed by the INSERT trigger.
 PERFORM set_config(
   'welcome_funnel.recovery_lock_conversation_id',
   p_conversation_id::text,
   true
 );

 PERFORM set_config(
   'welcome_funnel.recovery_lock_holder',
   p_holder,
   true
 );

 INSERT INTO public.agent_generation_locks(
   conversation_id,
   holder,
   acquired_at
 )
 VALUES(
   p_conversation_id,
   p_holder,
   now()
 );

 -- Clear eagerly as defense in depth. SET LOCAL also guarantees transaction
 -- cleanup if the INSERT raises and the transaction aborts.
 PERFORM set_config(
   'welcome_funnel.recovery_lock_conversation_id',
   '',
   true
 );

 PERFORM set_config(
   'welcome_funnel.recovery_lock_holder',
   '',
   true
 );

 RETURN true;
END;
$$;

REVOKE ALL
ON FUNCTION public.acquire_recovered_welcome_funnel_lock(
 uuid,uuid,uuid,uuid,uuid,text
)
FROM PUBLIC,anon,authenticated;

GRANT EXECUTE
ON FUNCTION public.acquire_recovered_welcome_funnel_lock(
 uuid,uuid,uuid,uuid,uuid,text
)
TO service_role;
